{
	"version": 1537363602,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bg1-sheet0.png",
		"images/play-sheet0.png",
		"images/bglevel1-sheet0.png",
		"images/bglv1-sheet0.png",
		"images/bgg-sheet0.png",
		"images/sprite-sheet0.png",
		"images/พื้น-sheet0.png",
		"images/hero-sheet0.png",
		"images/hero-sheet1.png",
		"images/พื้น2-sheet0.png",
		"images/กำแพง-sheet0.png",
		"images/หนาม-sheet0.png",
		"images/คะแนน-sheet0.png",
		"images/gov-sheet0.png",
		"images/menu-sheet0.png",
		"images/restart-sheet0.png",
		"images/bg3-sheet0.png",
		"images/พื้น3-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/pop-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite16-sheet1.png",
		"media/coins in hand 03.m4a",
		"media/coins in hand 03.ogg",
		"media/1.m4a",
		"media/1.ogg",
		"media/2.m4a",
		"media/2.ogg",
		"media/3.m4a",
		"media/3.ogg",
		"media/queen - we are the champions (chorus only) (128  kbps) (greenmp3.com).m4a",
		"media/queen - we are the champions (chorus only) (128  kbps) (greenmp3.com).ogg",
		"media/karaoke the final countdown - europe _ (128  kbps) (greenmp3.com).m4a",
		"media/karaoke the final countdown - europe _ (128  kbps) (greenmp3.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}